--- /home/mshanmu/git_workspace/mshanmu/operator-v4.4.14/helm/minio-operator/templates/console-ingress.yaml	2022-12-26 15:04:28.056541631 -0500
+++ console-ingress.yaml	2022-12-24 14:15:26.671424320 -0500
@@ -1,11 +1,5 @@
 {{- if .Values.console.ingress.enabled }}
-{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
 apiVersion: networking.k8s.io/v1
-{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
-apiVersion: networking.k8s.io/v1beta1
-{{- else -}}
-apiVersion: extensions/v1beta1
-{{- end }}
 kind: Ingress
 metadata:
   name: {{ include "minio-operator.console-fullname" . }}
@@ -17,13 +11,16 @@
   annotations: {{ toYaml . | nindent 4 }}
   {{- end }}
 spec:
+  {{- if .Values.console.ingress.ingressClassName }}
+  ingressClassName: {{ .Values.console.ingress.ingressClassName }}
+  {{- end }}
   {{- if .Values.console.ingress.tls }}
   tls:
     {{- range .Values.console.ingress.tls }}
     - hosts:
         {{- range .hosts }}
         - {{ . | quote }}
-      {{- end }}
+        {{- end }}
       secretName: {{ .secretName }}
     {{- end }}
   {{- end }}
@@ -32,16 +29,10 @@
       http:
         paths:
           - path: {{ .Values.console.ingress.path }}
-            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
-            pathType: Prefix
+            pathType: {{ .Values.console.ingress.pathType }}
             backend:
               service:
                 name: "console"
                 port:
                   name: http
-            {{- else }}
-            backend:
-              serviceName: "console"
-              servicePort: http
-            {{ end }}
 {{ end }}
