diff --git a/helm/minio-operator/templates/console-serviceaccount.yaml b/helm/minio-operator/templates/console-serviceaccount.yaml
new file mode 100644
index 0000000..a19e58a
--- /dev/null
+++ b/helm/minio-operator/templates/console-serviceaccount.yaml
@@ -0,0 +1,4 @@
+apiVersion: v1
+kind: ServiceAccount
+metadata:
+  name: console-sa
