diff --git a/helm/minio-operator/templates/console-clusterrolebinding.yaml b/helm/minio-operator/templates/console-clusterrolebinding.yaml
new file mode 100644
index 0000000..ae8b447
--- /dev/null
+++ b/helm/minio-operator/templates/console-clusterrolebinding.yaml
@@ -0,0 +1,12 @@
+apiVersion: rbac.authorization.k8s.io/v1
+kind: ClusterRoleBinding
+metadata:
+  name: console-sa-binding
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: console-sa-role
+subjects:
+  - kind: ServiceAccount
+    name: console-sa
+    namespace: {{ .Release.Namespace }}
